# Generated by Django 5.1 on 2024-11-13 06:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqam formati '+999999999' bo'lishi va 12 ta raqamdan oshmasligi kerak.", regex='^\\+?1?\\d{9,12}$')], verbose_name='Telefon raqam')),
                ('rating', models.FloatField(default=3, help_text="Reyting 0 va 5 orasida bo'lishi kerak.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Reyting')),
                ('image', models.ImageField(upload_to='category_images/', verbose_name='Rasm')),
                ('delivery_time', models.DurationField(verbose_name='Yetkazib berish vaqti')),
                ('working_time', models.TimeField(verbose_name='Ish vaqti')),
                ('category_type', models.CharField(choices=[('Store', 'Store'), ('Restaurant', 'Restaurant')], max_length=255, verbose_name='Store turi')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='common.address', verbose_name='Manzil')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='subcategory_images/', verbose_name='Rasm')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'SubStore',
                'verbose_name_plural': 'SubStores',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Narxi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Rasm')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Soni')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.subcategory', verbose_name='SubStore')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
    ]
