# Generated by Django 5.1 on 2024-11-13 10:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqam formati '+999999999' bo'lishi va 12 ta raqamdan oshmasligi kerak.", regex='^\\+?1?\\d{9,12}$')], verbose_name='Telefon raqam')),
                ('rating', models.FloatField(default=3, help_text="Reyting 0 va 5 orasida bo'lishi kerak.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Reyting')),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurant_images/', verbose_name='Rasm')),
                ('delivery_time', models.DurationField(blank=True, null=True, verbose_name='Yetkazib berish vaqti')),
                ('working_time', models.TimeField(blank=True, null=True, verbose_name='Ish vaqti')),
                ('cuisine_type', models.CharField(max_length=255, verbose_name='Taom turi')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='common.address', verbose_name='Manzil')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
    ]
