# Generated by Django 5.1.2 on 2024-10-28 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='rating',
            field=models.FloatField(default=3, help_text="Reyting 0 va 5 orasida bo'lishi kerak.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Reyting'),
        ),
    ]
