# Generated by Django 5.1.2 on 2024-11-08 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accaunt', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
