# Generated by Django 5.1.2 on 2024-11-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accaunt', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
